# Generated by Django 5.1.7 on 2025-04-06 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('os_info', models.CharField(max_length=255)),
                ('cpu_cores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('cpu_usage', models.FloatField(help_text='Overall CPU usage percentage')),
                ('memory_total', models.BigIntegerField(help_text='Total memory in bytes')),
                ('memory_used', models.BigIntegerField(help_text='Used memory in bytes')),
                ('memory_percent', models.FloatField(help_text='Memory usage percentage')),
                ('disk_total', models.BigIntegerField(help_text='Total disk space in bytes')),
                ('disk_used', models.BigIntegerField(help_text='Used disk space in bytes')),
                ('disk_percent', models.FloatField(help_text='Disk usage percentage')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='metrics.host')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['host', 'timestamp'], name='metrics_sys_host_id_e45f13_idx'), models.Index(fields=['timestamp'], name='metrics_sys_timesta_fcfdc7_idx')],
            },
        ),
    ]
